server:
  port: 8080

spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/${DB_NAME}
    username: ${DB_USER}
    password: ${DB_PASSWORD}
    driver-class-name: org.postgresql.Driver
  sql:
    init:
      mode: always
  flyway:
    enabled: true
  cache:
    type: redis
  security:
    jwt:
      secret-key: ${JWT_SECRET_KEY}
  data:
    redis:
      host: redis
      port: 6379

jwt:
  secret: ${JWT_SECRET_KEY}
  expiration: 600000 # 10 min
  refreshExpiration: 86400000 # 1 day